### ISSUE TITLE
Arte +7 Plugin 0.4.0 is broken since today

### ISSUE THREAD

**Issue by heziegl** [known-as-bmf/plugin.video.arteplussept#10]
Since today loading Arte video lists doesn't work any more. 
I'm using OpenELEC 6.0 beta 5 on Raspberry Pi and also checked it with a clean Kodi 15.2 installation on Windows with Arte +7 0.4.0.
I assume Arte changed its APIs.

log file:
20:04:09 T:15356  NOTICE: -->Python Interpreter Initialized<--
20:04:10 T:15356  NOTICE: [xbmcswift2] Request for "/new" matches rule for function "list"
20:04:10 T:15356   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.arteplussept\addon.py", line 233, in <module>
                                                plugin.run()
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.arteplussept\addon.py", line 114, in list
                                                data = load_json(json_url.format(lang=language), payload)
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\plugin.video.arteplussept\addon.py", line 229, in load_json
                                                return r.json()
                                              File "C:\Users\Test\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 805, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
20:04:10 T:3508   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.arteplussept/new
20:04:10 T:3508   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.arteplussept/new) failed

**Comment by known-as-bmf** [comment]
Thanks for reporting the issue, I'm working on it !

**Comment by known-as-bmf** [comment]
Fixed it with e3ab15c.

Could you install and test it on your setup before I push it to the addon repo ?

**Comment by heziegl** [comment]
Tested it on Windows and RaspberryPi and it worked!! Great! Thank you very much for providing a fix that fast :-)

**Comment by heziegl** [comment]
I used HTTP as selected protocol for testing and this worked.
With RTMP I get an error. Dont know if this worked with 0.4.0 before, since I always used HTTP.
This is not a big problem for me, since HTTP works perfectly fine for me. Just FYI.
Thanks.

**Comment by ElmarSieke** [comment]
Great job! Many thanks. Works fine for me:
RPI
Linux OpenELEC 3.17.8 #1 Tue Mar 31 16:15:02 CEST 2015 armv6l GNU/Linux

**Comment by simondubois** [comment]
Hi @known-as-bmf thank you for maintaining this add-on.
Do you have any idea when version 0.5 will be pushed to kodi repositories ?
I am still using version 0.4 (on Kodi 15.2)

**Comment by bcontins** [comment]
Tested commit e3ab15c on Raspberry Pi 2 (armv7l) with Kodi 14.2 / OpenElec 5.0.8. Seems to be working fine. Thanks for the quick fix.

**Comment by elouet** [comment]
Works for me too. Thanks very much !

**Comment by known-as-bmf** [comment]
Thanks everyone.

@simondubois I pushed it yesterday, it should be updated soon (1 week max).
