### ISSUE TITLE
Arte & Arte+7

### ISSUE THREAD

**Issue by regpa** [known-as-bmf/plugin.video.arteplussept#15]
Hi all, on osmc I have tries these two add-ons from two sources: 1/know-as-bmf (from standard kodi rep) & 2/addon-scriptorDE (from gotham rep). none of the 4 possibilities works. (Arte.tv error see the log, etc.)
 
would you have an idea of I should do to make it work ?

regpa

**Comment by known-as-bmf** [comment]
Hey

I had never heard of OSMC before, thanks for the discovery :)

Unfortunately, I don't have a Pi to reproduce this error.

Joining the content of the log file after a crash would be really helpfull in determining its cause.

Try these steps :
* Launch XBMC / Kodi
* Launch / Browse the addon until a crash happens
* Open the log file and copy / paste the error here (it should be near the end of the file)

Thank you for your feedback !

**Comment by regpa** [comment]
Hey known-as-bmf,

now arte+7 addon works well (great!!!), however arte.tv don't, here is the log: 
thanks a lot for arte+7 !!!
regpa


21:43:12 155.874039 T:1591735328  NOTICE: -->Python Interpreter Initialized<--
21:43:14 157.085297 T:1591735328  NOTICE: CommonFunctions-2.5.1
21:43:14 157.554214 T:1591735328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.arte_tv/default.py", line 420, in <module>
                                                listVideosNew(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.arte_tv/default.py", line 65, in listVideosNew
                                                content = getUrl(url)
                                              File "/home/osmc/.kodi/addons/plugin.video.arte_tv/default.py", line 365, in getUrl
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
21:43:14 157.677460 T:1958462000   ERROR: GetDirectory - Error getting plugin://plugin.video.arte_tv/?mode=listVideosNew&regionFilter&url=http%3a%2f%2fwww.arte.tv%2fguide%2ffr%2fplus7%2fplus_recentes.json%3fregions%3dALL%252Cdefault%252CDE_FR%252CSAT%252CEUR_DE_FR
21:43:14 157.680450 T:1958462000   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.arte_tv/?mode=listVideosNew&regionFilter&url=http%3a%2f%2fwww.arte.tv%2fguide%2ffr%2fplus7%2fplus_recentes.json%3fregions%3dALL%252Cdefault%252CDE_FR%252CSAT%252CEUR_DE_FR) failed
21:43:14 157.695831 T:1591735328  NOTICE: Thread BackgroundLoader start, auto delete: false
21:43:20 163.407608 T:1591735328  NOTICE: Previous line repeats 1 times.
21:43:20 163.407883 T:1591735328  NOTICE: Thread LanguageInvoker start, auto delete: false

**Comment by known-as-bmf** [comment]
I'm glad the Arte +7 addon works for you now !

Unfortunatelly, I can't give you support for the Arte.tv addon as I am not involved in it's developement.

Hopefully, Arte +7's features will fulfill your needs.
