### ISSUE TITLE
Error on recording

### ISSUE THREAD

**Issue by Acteo** [known-as-bmf/plugin.video.arteplussept#17]
Hello,
Thanks for the job.
I tried to download my favorite tv series without succes

this is a part of the log
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 52: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.video.arteplussept\addon.py", line 310, in <module>
                                                plugin.run()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.video.arteplussept\addon.py", line 209, in download_file
                                                plugin.notify(filename, plugin.get_string(30010))
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\xbmcmixin.py", line 300, in notify
                                                (msg, title, delay, image))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 52: ordinal not in range(128)
                                            -->End of Python script error report<--
____________________________________________________

what did i do wrong ?
any idea ?

**Comment by known-as-bmf** [comment]
Hey, 0.5.2 should fix it.

It was (maybe still is :/) an encoding problem with the strings displayed in the download notification (bottom right popup).

**Comment by hstraub** [comment]
Hallo again,

I think the solution should be found in http://kodi.wiki/view/Add-on_unicode_paths . If the content from the server contains utf-8 encoding, then we should convert it.
