### ISSUE TITLE
The "Live" doesn't work anymore

### ISSUE THREAD

**Issue by NerosTie** [known-as-bmf/plugin.video.arteplussept#26]
When I click on "Live", it fails (on my raspberry pi and my computer)

Here the log:

```
15:01:47 45642.203125 T:1708127216   DEBUG: [xbmcswift2] Handling incoming request for /live
15:01:47 45642.203125 T:1708127216  NOTICE: [xbmcswift2] Request for "/live" matches rule for function "play_live"
15:01:47 45642.218750 T:1956799408   DEBUG: DialogProgress::Open called
15:01:47 45642.218750 T:1956799408   DEBUG: ------ Window Init (DialogProgress.xml) ------
15:01:48 45642.394531 T:1708127216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/addon.py", line 357, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.arteplussept/addon.py", line 232, in play_live
                                                url = data['video']['VSR'][1]['VUR']
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
15:01:48 45642.394531 T:1956799408   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
15:01:48 45642.507812 T:1708127216    INFO: Python script stopped
15:01:48 45642.507812 T:1708127216   DEBUG: Thread LanguageInvoker 1708127216 terminating
15:01:48 45642.582031 T:1956799408   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
15:01:48 45642.582031 T:1956799408   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.arteplussept/live]
15:01:48 45642.582031 T:1956799408   DEBUG: Playlist Player: one or more items failed to play... aborting playback
15:01:48 45642.582031 T:1956799408   DEBUG: ------ Window Init (DialogOK.xml) ------
15:01:48 45642.582031 T:1956799408    INFO: Loading skin file: DialogOK.xml, load type: KEEP_IN_MEMORY
15:01:48 45642.589844 T:1956799408   DEBUG: ------ Window Deinit (DialogProgress.xml) ------
15:01:53 45647.886719 T:1956799408   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
15:01:53 45647.906250 T:1632629744   DEBUG: Thread JobWorker 1632629744 terminating (autodelete)
15:01:58 45652.378906 T:1632629744   DEBUG: webserver: request received for /jsonrpc
15:01:58 45652.500000 T:1956799408   DEBUG: Previous line repeats 6 times.
15:01:58 45652.500000 T:1956799408   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
15:01:58 45652.503906 T:1956799408   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
15:01:58 45652.507812 T:1421325296   DEBUG: webserver: request received for /jsonrpc
```

**Comment by Furlot** [comment]
in file  .kodi/addons/plugin.video.arteplussept/addon.py
line 232 :  url = data['video']['VSR'][1]['VUR'] 
replace 1 with 0 like this :  url = data['video']['VSR'][0]['VUR']

**Comment by NerosTie** [comment]
It works, thanks @Furlot

**Comment by RaumZeit** [comment]
Still won't work for me, unfortunately. I've change the array index from 1 to 0 which removes the out-of-bounds issue. But now, URL resolving seems to fail. Here is my log output:
```
13:29:04 5682.201172 T:1380967328   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
13:29:04 5682.201172 T:1380967328   ERROR: CCurlFile::Open failed with code 0 for http://artelive-http//artelive-lh.akamaihd.net/i/artelive_de@393591/master.
m3u8
```
Any advice?

**Comment by known-as-bmf** [comment]
Hey

Thanks @Furlot  for providing a fix :)

@RaumZeit I think this promlem was on arte's API side. Seems to be fixed now.
