### ISSUE TITLE
master branch has suddenly stopped working

### ISSUE THREAD

**Issue by oliviercommelarbre** [known-as-bmf/plugin.video.arteplussept#46]
Hi, since a few days the master version suddenly stopped working, something must have changed on Arte's side

here the log when the addon is triggered:
```
00:38:05.984 T:140735289835520   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
00:38:06.365 T:123145304526848  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
00:38:06.527 T:123145304526848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 106, in <module>
                                                plugin.run()
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 57, in index
                                                return [mapper.map_index_item(app_name, config) for app_name, config in api.apps().iteritems()]
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/plugin.video.arteplussept/resources/lib/api.py", line 23, in apps
                                                return _load_json(url).get('apps', {})
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/plugin.video.arteplussept/resources/lib/api.py", line 51, in _load_json
                                                return r.json(object_pairs_hook=OrderedDict)
                                              File "/Users/<user>/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/models.py", line 892, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/json/__init__.py", line 352, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
00:38:06.655 T:140735289835520   ERROR: GetDirectory - Error getting plugin://plugin.video.arteplussept/
00:38:06.656 T:140735289835520   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.arteplussept/) failed
```
I've since reverted to the 0.5.8 and it still works

**Comment by known-as-bmf** [comment]
I pushed a fix on master, tell me if it works on your side

**Comment by oliviercommelarbre** [comment]
thanks YOU so much for getting it back so quickly!
yes, problem solved on my side, and i actually discover the new 1.0, i was sofar using your previous rewrite branch youposted earlier this year (that stopped working at the same time which brought me to find the new one). now with even nicer and intuitive navigation than ever!
thanks for the brilliant work you share

**Comment by known-as-bmf** [comment]
I pushed version 1.0.1 on the official repo, it should work fine 👍

I still have to implement "creative" and localize some labels but that will come later !
