### ISSUE TITLE
Kodi 19 Matrix crash

### ISSUE THREAD

**Issue by PiotrC1** [known-as-bmf/plugin.video.arteplussept#73]
Plugin is unable to start streaming. In log following can be found:

```
2021-03-05 16:41:04.897 T:11138   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 130, in <module>
                                                       plugin.run()
                                                     File "/home/zenon/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "/home/zenon/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/addon.py", line 90, in sub_category_by_title
                                                       return plugin.finish(view.build_sub_category_by_title(category_code, sub_category_title, settings))
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/view.py", line 59, in build_sub_category_by_title
                                                       return [mapper.map_generic_item(item, settings.show_video_streams) for item in sub_category.get('teasers')]
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/view.py", line 59, in <listcomp>
                                                       return [mapper.map_generic_item(item, settings.show_video_streams) for item in sub_category.get('teasers')]
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/mapper.py", line 78, in map_generic_item
                                                       return map_video(item, show_video_streams)
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/mapper.py", line 93, in map_video
                                                       'label': utils.format_title_and_subtitle(item.get('title'), item.get('subtitle')),
                                                     File "/home/zenon/.kodi/addons/plugin.video.arteplussept/resources/lib/utils.py", line 23, in format_title_and_subtitle
                                                       label = u'[B]{title}[/B]'.format(title=p.unescape(title))
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
                                                   
2021-03-05 16:41:04.934 T:11138    INFO <general>: Python interpreter stopped
```

**Comment by known-as-bmf** [comment]
Looking into it.

Could you share more context ? Where were you navigating when the crash happened, how did you install the add-on, the version of `xbmc.python` used...

Look for the line that looks like 
> 2021-03-05 18:01:28.993 T:12468    INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: xbmc.python v3.0.0 installed

in the logs

**Comment by PiotrC1** [comment]
A little bit more details:
Kodi 19 (Matrix) on ArchLinux `Linux XXXXX 5.11.2-arch1-1 #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000 x86_64 GNU/Linux`
```
    <requires>
        <import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.module.xbmcswift2" version="19.0.4"/>
        <import addon="script.module.requests" version="2.22.0"/>
    </requires>
```
`
19.0 (19.0.0) Git:20210304-nogitfound Media Center Kodi
`
`Python 3.9.2`

**Comment by known-as-bmf** [comment]
I updated the add-on and opened a pull request (https://github.com/xbmc/repo-plugins/pull/3442) to the official repo.

When the add-on gets updated, check and see if the problem persists. New version should be `1.1.1`.

**Comment by PiotrC1** [comment]
Updated from github directly. Seems to work fluently. Thanks.
